# Generated by Django 4.2.2 on 2023-06-15 12:09

import car_shop_exam.web.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Sports Car', 'Sports Car'), ('Pickup', 'Pickup'), ('Crossover', 'Crossover'), ('Minibus', 'Minibus'), ('Other', 'Other')], max_length=10, verbose_name='Type')),
                ('model', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Model')),
                ('year', models.IntegerField(validators=[car_shop_exam.web.models.year_check], verbose_name='Year')),
                ('image_url', models.URLField(verbose_name='Image Url')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Price')),
            ],
        ),
    ]
