# Generated by Django 4.2.4 on 2023-08-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcription',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
