# Generated by Django 4.2.2 on 2023-06-21 09:17

import django.core.validators
from django.db import migrations, models
import my_music_app.web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=30, unique=True, verbose_name='Album Name')),
                ('artist', models.CharField(max_length=30, verbose_name='Artist')),
                ('genre', models.CharField(choices=[('Hip Hop Music', 'Hip Hop Music'), ('Country Music', 'Country Music'), ('Rock Music', 'Rock Music'), ('Jazz Music', 'Jazz Music'), ('Other', 'Other'), ('R&B Music', 'R&B Music'), ('Dance Music', 'Dance Music'), ('Pop Music', 'Pop Music')], max_length=30, verbose_name='Genre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image_url', models.URLField(verbose_name='Image URL')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, 'The price cannot be below 0.0')])),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), my_music_app.web.models.only_letters_validator], verbose_name='Username')),
                ('email', models.EmailField(max_length=254)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
