# Generated by Django 4.2 on 2023-06-22 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GamesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=30, unique=True, verbose_name="Title"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Action", "Action"),
                            ("Adventure", "Adventure"),
                            ("Puzzle", "Puzzle"),
                            ("Strategy", "Strategy"),
                            ("Sports", "Sports"),
                            ("Board/Card Game", "Board/Card Game"),
                            ("Other", "Other"),
                        ],
                        max_length=15,
                        verbose_name="Category",
                    ),
                ),
                (
                    "rating",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                        verbose_name="Rating",
                    ),
                ),
                (
                    "max_level",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Max Level",
                    ),
                ),
                ("image_url", models.URLField(verbose_name="Image URL")),
                ("summary", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
