# Generated by Django 4.2.2 on 2023-06-06 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_profile_first_name_alter_profile_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_type', models.CharField(choices=[('Outdoor Plants', 'Outdoor Plants'), ('Indoor Plants', 'Indoor Plants')], max_length=14, verbose_name='Plan Type')),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Name')),
                ('image_url', models.URLField(verbose_name='Image Url')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.FloatField(verbose_name='Price')),
            ],
        ),
    ]
