# Generated by Django 4.2.3 on 2023-07-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='followers_count',
            field=models.IntegerField(default=0),
        ),
    ]
